# Basic Information 
title: Dong Chen 陈栋
position: Assistant Professor 助理研究员
affiliation: Institute of Psychology, CAS 中国科学院心理研究所
email: chend@psych.ac.cn

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: minimal light # need not change
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage. # need not change
canonical: https://minimal-light-theme.yliu.me/ # need not change

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?hl=en&user=AzL39ZoAAAAJ&view_op=list_works
research_gate: https://www.researchgate.net/profile/Dong-Chen-68
#cv_link: files/Curriculum_Vitae.pdf # put CV here `assets/files/Curriculum_Vitae.pdf`
github_link: https://github.com/chendong567/
#linkedin: https://www.linkedin.com/
#twitter: https://twitter.com/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.jpg # profile picture
favicon: ./assets/img/favicon.png # need not change
favicon_dark: ./assets/img/favicon-dark.png # need not change

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true # need not change

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: false # need not change

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif" # need not change

# The following files will be removed from the generated website.
# need not change
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
